import fs from "node:fs/promises";
import path from "node:path";
import fg from "fast-glob";

import type { FileStat } from "./types.js";
import { estimateTokens } from "./tokenizer.js";

const CODE_EXTENSIONS = new Set([
  ".js",
  ".jsx",
  ".ts",
  ".tsx",
  ".mjs",
  ".cjs",
  ".py",
  ".java",
  ".go",
  ".rs",
  ".cpp",
  ".cc",
  ".c",
  ".h",
  ".hpp",
  ".cs",
  ".rb",
  ".php",
  ".swift",
  ".kt",
  ".kts",
  ".scala",
  ".sh",
  ".sql",
  ".vue",
  ".svelte",
]);

const IGNORED_DIRECTORIES = [
  "**/node_modules/**",
  "**/.git/**",
  "**/.svn/**",
  "**/.hg/**",
  "**/dist/**",
  "**/build/**",
  "**/coverage/**",
  "**/.next/**",
  "**/.nuxt/**",
  "**/.turbo/**",
  "**/vendor/**",
  "**/target/**",
];



function isGeneratedFile(filePath: string, content: string): boolean {
    const name = path.basename(filePath).toLowerCase();
  
    const generatedName =
      name.includes("generated") ||
      name.includes("autogenerated") ||
      name.includes(".gen.");
  
    const header = content
      .split("\n")
      .slice(0, 10)
      .join("\n")
      .toUpperCase();
  
    const generatedMarker =
      header.includes("DO NOT EDIT") ||
      header.includes("AUTO-GENERATED") ||
      header.includes("GENERATED FILE");
  
    return generatedName || generatedMarker;
}

export async function scanRepository(root: string): Promise<FileStat[]> {
  const files = await fg(
    [
      "**/*",
      ...Array.from(CODE_EXTENSIONS).map((ext) => `**/*${ext}`),
    ],
    {
      cwd: root,
      absolute: true,
      onlyFiles: true,
      ignore: IGNORED_DIRECTORIES,
      unique: true,
    }
  );

  const stats: FileStat[] = [];

  for (const file of files) {
    const extension = path.extname(file).toLowerCase();

    if (!CODE_EXTENSIONS.has(extension)) {
      continue;
    }

    const content = await fs.readFile(file, "utf8");

    stats.push({
      path: path.relative(root, file),
      extension,
      bytes: Buffer.byteLength(content),
      estimatedTokens: estimateTokens(content),
      isGenerated: isGeneratedFile(file, content),
    });
  }

  return stats.sort(
    (a, b) => b.estimatedTokens - a.estimatedTokens
  );
}